import { ShionBizCode } from './shion-biz-code.enum'
import { HttpStatus } from '@nestjs/common'

export const ShionBizCodeHttpStatus: Record<ShionBizCode, HttpStatus> = {
  [ShionBizCode.COMMON_SUCCESS]: HttpStatus.OK,

  // 10
  [ShionBizCode.COMMON_VALIDATION_FAILED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ShionBizCode.COMMON_NOT_IMPLEMENTED]: HttpStatus.NOT_IMPLEMENTED,

  // 20
  [ShionBizCode.AUTH_UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
  [ShionBizCode.AUTH_INVALID_TOKEN]: HttpStatus.UNAUTHORIZED,
  [ShionBizCode.AUTH_INVALID_REFRESH_TOKEN]: HttpStatus.UNAUTHORIZED,
  [ShionBizCode.AUTH_REFRESH_TOKEN_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [ShionBizCode.AUTH_REFRESH_TOKEN_REUSED]: HttpStatus.UNAUTHORIZED,
  [ShionBizCode.AUTH_FAMILY_BLOCKED]: HttpStatus.FORBIDDEN,
  [ShionBizCode.AUTH_VERIFICATION_CODE_NOT_FOUND_OR_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [ShionBizCode.AUTH_VERIFICATION_CODE_ERROR]: HttpStatus.UNAUTHORIZED,

  // 30
  [ShionBizCode.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.USER_EMAIL_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [ShionBizCode.USER_NAME_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [ShionBizCode.USER_NOT_ALLOW_REGISTER]: HttpStatus.FORBIDDEN,
  [ShionBizCode.USER_BANNED]: HttpStatus.FORBIDDEN,
  [ShionBizCode.USER_INVALID_PASSWORD]: HttpStatus.UNAUTHORIZED,
  [ShionBizCode.USER_INVALID_LANG]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ShionBizCode.USER_INVALID_CONTENT_LIMIT]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ShionBizCode.USER_ALREADY_BANNED]: HttpStatus.CONFLICT,
  [ShionBizCode.USER_ALREADY_UNBANNED]: HttpStatus.CONFLICT,
  [ShionBizCode.USER_INVALID_BAN_DURATION]: HttpStatus.UNPROCESSABLE_ENTITY,

  // 40
  [ShionBizCode.GAME_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.GAME_INVALID_VNDB_ID]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ShionBizCode.GAME_BANGUMI_REQUEST_FAILED]: HttpStatus.BAD_GATEWAY,
  [ShionBizCode.GAME_VNDB_REQUEST_FAILED]: HttpStatus.BAD_GATEWAY,
  [ShionBizCode.GAME_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [ShionBizCode.GAME_DATA_CONSISTENCY_CHECK_FAILED]: HttpStatus.BAD_REQUEST,

  // 41
  [ShionBizCode.GAME_DEVELOPER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.GAME_DEVELOPER_ALREADY_EXISTS]: HttpStatus.CONFLICT,

  // 42
  [ShionBizCode.GAME_CHARACTER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.GAME_CHARACTER_ALREADY_EXISTS]: HttpStatus.CONFLICT,

  // 43
  [ShionBizCode.GAME_COVER_ALREADY_EXISTS]: HttpStatus.CONFLICT,

  // 44
  [ShionBizCode.GAME_DOWNLOAD_RESOURCE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.GAME_DOWNLOAD_RESOURCE_NOT_OWNER]: HttpStatus.FORBIDDEN,

  // 45
  [ShionBizCode.GAME_DOWNLOAD_RESOURCE_FILE_NOT_FOUND]: HttpStatus.NOT_FOUND,

  // 46
  [ShionBizCode.FAVORITE_ALREADY_EXISTS]: HttpStatus.CONFLICT,

  // 47
  [ShionBizCode.COMMENT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.COMMENT_NOT_OWNER]: HttpStatus.FORBIDDEN,
  [ShionBizCode.COMMENT_TOO_DEEP]: HttpStatus.BAD_REQUEST,

  // 48
  [ShionBizCode.GAME_UPLOAD_INVALID_TOTAL_SIZE]: HttpStatus.BAD_REQUEST,
  [ShionBizCode.GAME_UPLOAD_TOO_MANY_CHUNKS]: HttpStatus.BAD_REQUEST,
  [ShionBizCode.GAME_UPLOAD_TOO_LARGE]: HttpStatus.BAD_REQUEST,
  [ShionBizCode.GAME_UPLOAD_SESSION_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.GAME_UPLOAD_INVALID_SESSION_STATUS]: HttpStatus.CONFLICT,
  [ShionBizCode.GAME_UPLOAD_UNEXPECTED_CONTENT_LENGTH]: HttpStatus.BAD_REQUEST,
  [ShionBizCode.GAME_UPLOAD_INVALID_CHUNK_SHA256]: HttpStatus.CONFLICT,
  [ShionBizCode.GAME_UPLOAD_CHUNK_SHA256_MISMATCH]: HttpStatus.CONFLICT,
  [ShionBizCode.GAME_UPLOAD_INCOMPLETE]: HttpStatus.CONFLICT,
  [ShionBizCode.GAME_UPLOAD_FILE_SHA256_MISMATCH]: HttpStatus.CONFLICT,
  [ShionBizCode.GAME_UPLOAD_INVALID_CHUNK_INDEX]: HttpStatus.BAD_REQUEST,
  [ShionBizCode.GAME_UPLOAD_SESSION_EXPIRED]: HttpStatus.GONE,
  [ShionBizCode.GAME_UPLOAD_SESSION_NOT_OWNER]: HttpStatus.FORBIDDEN,

  // 49
  [ShionBizCode.SMALL_FILE_UPLOAD_FILE_SIZE_EXCEEDS_LIMIT]: HttpStatus.PAYLOAD_TOO_LARGE,
  [ShionBizCode.SMALL_FILE_UPLOAD_FILE_NO_FILE_PROVIDED]: HttpStatus.BAD_REQUEST,
  [ShionBizCode.SMALL_FILE_UPLOAD_UNSUPPORTED_FILE_TYPE]: HttpStatus.UNSUPPORTED_MEDIA_TYPE,

  // 50
  [ShionBizCode.USER_UPLOAD_QUOTA_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.USER_UPLOAD_QUOTA_EXCEEDED]: HttpStatus.CONFLICT,
  [ShionBizCode.USER_UPLOAD_QUOTA_USE_CANT_BE_NEGATIVE]: HttpStatus.CONFLICT,
  [ShionBizCode.USER_UPLOAD_QUOTA_RECORD_NOT_FOUND]: HttpStatus.NOT_FOUND,

  // 51
  [ShionBizCode.EDIT_FIELD_PERMISSION_NOT_ENOUGH]: HttpStatus.FORBIDDEN,

  // 52
  [ShionBizCode.EDIT_RECORD_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ShionBizCode.EDIT_RECORD_ALREADY_UNDONE]: HttpStatus.CONFLICT,
  [ShionBizCode.EDIT_RECORD_CONFLICT]: HttpStatus.CONFLICT,
} as const satisfies Record<ShionBizCode, HttpStatus>
