export const S3_IMAGE_CLIENT = 'S3_IMAGE_CLIENT'
export const S3_GAME_CLIENT = 'S3_GAME_CLIENT'
export const S3_BACKUP_CLIENT = 'S3_BACKUP_CLIENT'

export const IMAGE_STORAGE = 'IMAGE_STORAGE'
export const GAME_STORAGE = 'GAME_STORAGE'
export const BACKUP_STORAGE = 'BACKUP_STORAGE'
