// "harassment": false,
// "harassment/threatening": false,
// "sexual": false,
// "hate": false,
// "hate/threatening": false,
// "illicit": false,
// "illicit/violent": false,
// "self-harm/intent": false,
// "self-harm/instructions": false,
// "self-harm": false,
// "sexual/minors": false,
// "violence": false,
// "violence/graphic": false

export enum ModerateCategory {
  HARASSMENT = 'harassment',
  HARASSMENT_THREATENING = 'harassment/threatening',
  SEXUAL = 'sexual',
  HATE = 'hate',
  HATE_THREATENING = 'hate/threatening',
  ILLICIT = 'illicit',
  ILLICIT_VIOLENT = 'illicit/violent',
  SELF_HARM_INTENT = 'self-harm/intent',
  SELF_HARM_INSTRUCTIONS = 'self-harm/instructions',
  SELF_HARM = 'self-harm',
  SEXUAL_MINORS = 'sexual/minors',
  VIOLENCE = 'violence',
  VIOLENCE_GRAPHIC = 'violence/graphic',
}
