export enum EditActionType {
  UPDATE_SCALAR = 'UPDATE_SCALAR',
  ADD_RELATION = 'ADD_RELATION',
  REMOVE_RELATION = 'REMOVE_RELATION',
  SET_RELATION = 'SET_RELATION',
  UPDATE_RELATION = 'UPDATE_RELATION',
}
